name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Zig 0.16.0
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Build
        run: zig build

      - name: Test
        run: zig build test

      - name: Run Io.Threaded example
        run: zig build check-io-threaded

      - name: Build counter example
        run: zig build check-counter
